name: ventify_app
description: "Ventify - A safe space for emotional support."
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.1.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  # --- Storage & Security ---
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  flutter_secure_storage: ^9.0.0
  local_auth: ^2.1.0

  # --- Networking ---
  http: ^1.1.0

  # --- Utilities ---
  uuid: ^4.0.0
  path_provider: ^2.1.0
  intl: ^0.19.0

  # --- UI Assets ---
  cupertino_icons: ^1.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

  # --- Code Generation ---
  hive_generator: ^2.0.0
  build_runner: ^2.4.0

  # --- Icon Generator ---
  flutter_launcher_icons: ^0.13.1

flutter:
  uses-material-design: true
  assets:
    - assets/

# --- CONFIGURATION (Nasa Dulo) ---
flutter_launcher_icons:
  android: "launcher_icon"
  ios: false # <--- GINAWA NATING FALSE PARA HINDI NA HANAPIN ANG IPHONE FOLDER
  image_path: "assets/Venty1.png"
  min_sdk_android: 21
