name: ventify_app
description: "Ventify - A safe space for emotional support."
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.1.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  # --- Storage & Security (Local-First Privacy) ---
  hive: ^2.2.3 # Database natin (kapalit ng Firebase)
  hive_flutter: ^1.1.0 # Flutter integration ng Hive
  flutter_secure_storage: ^9.0.0 # Para sa encryption keys
  local_auth: ^2.1.0 # Fingerprint/Face Unlock

  # --- Networking (Para sa Railway) ---
  http: ^1.1.0 # Pang-connect sa API mo

  # --- Utilities ---
  uuid: ^4.0.0 # Unique ID generator
  path_provider: ^2.1.0 # Para mahanap kung saan mag-save sa phone
  intl: ^0.19.0 # Date formatting

  # --- UI Assets ---
  cupertino_icons: ^1.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  # --- Code Generation (Kailangan ng Hive) ---
  hive_generator: ^2.0.0
  build_runner: ^2.4.0

flutter:
  uses-material-design: true
  # Dito natin ilalagay ang assets at fonts sa susunod
